name: Generate config
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: npm run build
      - run: git status

      - run: echo Current ref is ${{ github.ref }}

      # if there is a change to the circle.yml file
      # then commit and push it. Only do this on "master" branch
      # https://github.com/mikeal/publish-to-github-action
      - uses: mikeal/publish-to-github-action@master
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Cypress Tests

    on: [push]

    jobs:
      cypress-run:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          # Install NPM dependencies, cache them correctly
          # and run all Cypress tests
          - name: Cypress run
            uses: cypress-io/github-action@v2
            with:
              build: npm run build
              start: npm start
